### ISSUE TITLE
Create default user with Nimble email

### ISSUE THREAD

**Issue by olivierobert** [nimblehq/nimble-survey-web#23]
## Why

Until sign up is enabled, users must use the user `hoangmirs@gmail.com`. But that's not ideal for both internal certifications or external recruitment use. So replace this user or create a new user with email `dev@nimblehq.co`. 
 
## Who Benefits?

Initially, this will be sufficient for internal certifications. For recruitment purposes, sign up must be added.

**Comment by hoangmirs** [comment]
Should we let users use `http://survey-api.nimblehq.co/users/sign_up`to register a new account themself?

**Comment by olivierobert** [comment]
Indeed 🤦  So I created the user `dev@nimblehq.co` and added it to 1Password.
