### ISSUE TITLE
User name and avatar

### ISSUE THREAD

**Issue by rafayet-monon** [nimblehq/nimble-survey-web#50]
The current Profile API only has an email associated with it and no option to add the avatar in the signup API. 
Profile API response -

![image](https://user-images.githubusercontent.com/14927672/102769574-0bb8dd80-43ad-11eb-8585-4a6944eed90d.png)

An user should have a short name and an avatar to align with the [design](https://www.figma.com/file/i1AI0IzCWuJApX5CK0DmiW/Challenge---Web-App?node-id=70%3A321) - 

![image](https://user-images.githubusercontent.com/14927672/102768979-335b7600-43ac-11eb-8314-89446cd047b5.png)

**Comment by sleepylee** [comment]
I agree...the avatar from `https://api.adorable.io/avatar/` always responds with a 1x1 white pixel - which makes the front-end app very ugly when crafted.

**Comment by hoangmirs** [comment]
This should be closed once we merge #61
