### ISSUE TITLE
Value Type of Identification in API Response

### ISSUE THREAD

**Issue by suho** [nimblehq/nimble-survey-web#58]
## Issue

Based on the document from jsonapi.org:
```
Every resource object MUST contain an id member and a type member. The values of the id and type members MUST be strings.
```

Here is the link: https://jsonapi.org/format/#document-resource-object-identification

Currently, the value type of `id` is `Int`

![Screen Shot 2021-06-17 at 19 04 29](https://user-images.githubusercontent.com/19943832/122393220-da594d00-cf9e-11eb-9fa7-734fdb932052.png)

## Expected

The value type of `id` should be `String

## Steps to reproduce

1. Login with API `{{base_url}}/api/v1/oauth/token`
2. Check the response

**Comment by suho** [comment]
@olivierobert Please help me to check this.

**Comment by hoangmirs** [comment]
@suho Let me check it
